services:
    Mpp\GeneraliClientBundle\HttpClient\GeneraliHttpClient:
        public: true
        arguments:
          - '@eight_points_guzzle.client.mpp_generali'
          - '@logger'

    Mpp\GeneraliClientBundle\HttpClient\GeneraliHttpClientV2:
        public: true
        arguments:
          - '@eight_points_guzzle.client.mpp_generali'
          - '@logger'
          - '%mpp_generali_client.app_code%'
          - '%mpp_generali_client.subscription_code%'

    Mpp\GeneraliClientBundle\PdfGenerator\GeneraliPdfGenerator:
        public: true
        arguments:
          - '@twig'
          - '@logger'
          - '@eight_points_guzzle.client.wkhtmltopdf'
          - '%generali_debit_mandate_template%'
          - '%generali_debit_mandate_export_path%'