services:
  mpp.http_client.generali:
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: '%env(GENRALI_BASE_URI)%'
        headers:
          apiKey: '%env(GENERALI_API_KEY)%'
          Accept:  'application/json'
          Content-Type: 'application/json'
        timeout: 30
        connect_timeout: 30
        read_timeout: 30
#        verify: false