services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mpp\GeneraliClientBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,vendor}'

    # Client
    _instanceof:
        Mpp\GeneraliClientBundle\Client\GeneraliClientInterface:
            tags: ['mpp_generali_client.client']
            bind:
                $logger: '@logger'
                $serializer: '@serializer'
                $defaultContext: '%mpp_generali_client.default_context%'

    Mpp\GeneraliClientBundle\Client\GeneraliClientRegistry: ~
    Mpp\GeneraliClientBundle\Client\GeneraliClientRegistryInterface: '@Mpp\GeneraliClientBundle\Client\GeneraliClientRegistry'

    Mpp\GeneraliClientBundle\Handler\ReferentialHandler: ~
